= JUnit 4 to Junit 5 Converter Plugin

== About

Convert your TestNG tests into JUnit 5 Jupiter.

In development.
More features to come.

=== Inspections

This plugin adds the following inspections in the `Java` / `TestNG` inspections group:

==== Convert TestNG assertion to JUnit 5

Triggers on any TestNG assertion usage, and suggest converting it to a JUnit 5 assertion. Provides a quick-fix to do the conversion.

==== Convert TestNG tests to JUnit 5

Triggers on any class that contains TestNG tests, and suggest converting the tests to JUnit 5. Provides a quick-fix to do the conversion.

=== Actions

This plugin does not add any action. If you need to convert many tests in a project, use the general `Code cleanup...` action with an inspection profile that contains the `Convert TestNG tests to JUnit 5` inspection.

== Developers

- Tommy Karlsson

== Acknowledgments

This plugin was built based on inspirations from:

- https://github.com/wlsc/idea-junit-5-converter-plugin[JUnit 4 to Junit 5 Converter Plugin] (author Wladimir Schmidt)
- The Intellij IDEA built-in JUnit 5 converter inspection.

== Known issues

- Conversion of `@Test.expectedExceptionsMessageRegExp` assumes that Hamcrest 2.0.0 or later is available. If it is not available, the assertion will not compile.